/*
 * This source file was generated by the Gradle 'init' task
 */
package com.github.k1mch1.mc;

import java.io.*;

public class Main {
  public static void main(String[] args) {
    System.out.println("Starting a new server...");
    File worldFile = new File("worlds/world.cw");
    System.out.println(worldFile.getAbsolutePath());
  }
}
